[package]
name = "polynomial-macro"
version = "1.0.0"
authors = ["Fabio Cardeal <ficarde@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6.9"
proc-macro2 = "0.4"

[dependencies.syn]
version = "0.15.26"
features = ["full"]
