[package]
name = "polysum_c"
version = "0.1.0"
authors = ["fcard"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
rug = "^1.3.0"
gmp-mpfr-sys = "^1.1.12"
polysum = { path = "../polysum" }

